global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "dr-exporter"
    static_configs:
      - targets: ["exporter:9090"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
